#!/usr/bin/env node
import { readFile } from 'node:fs/promises';
import { indexAndroidManifest } from './recovery/android-manifest';
import { recoverAndroid } from './recovery/android';
import { indexAndroidWorkspace } from './recovery/android-index';
import { rebuildAndroid } from './recovery/android-rebuild';
import { verifyAndroidRuntime } from './recovery/android-runtime';
import { signAndVerifyAndroid } from './recovery/android-verify';
import { indexDexFiles } from './recovery/dex';
import { rebuildElectron } from './recovery/electron-rebuild';
import { recoverMac } from './recovery/macos';
import { applyPatchPlan, PatchPlan } from './recovery/patch-plan';
import { generatePatchTemplate } from './recovery/patch-generator';
import { planVibePatch } from './recovery/vibe-planner';
async function main(){const [command,...args]=process.argv.slice(2);const value=(k:string)=>{const i=args.indexOf(k);return i>=0?args[i+1]:undefined};if(command==='recover-apk'&&args[0])return console.log(JSON.stringify(await recoverAndroid(args[0],args[1]||'recovered-workspace'),null,2));if(command==='index-android'&&args[0])return console.log(JSON.stringify(await indexAndroidWorkspace(args[0]),null,2));if(command==='index-manifest'&&args[0])return console.log(JSON.stringify(await indexAndroidManifest(args[0]),null,2));if(command==='index-dex'&&args.length>1)return console.log(JSON.stringify(await indexDexFiles(args.slice(0,-1),args.at(-1)!),null,2));if(command==='plan'&&args[0]&&args[1])return console.log(JSON.stringify(await planVibePatch(args[0],args[1]),null,2));if(command==='patch-template'&&args[0]&&args[1])return console.log(JSON.stringify(await generatePatchTemplate(args[0],args[1]),null,2));if(command==='patch'&&args[0]&&args[1]){const plan=JSON.parse(await readFile(args[0],'utf8')) as PatchPlan;return console.log(JSON.stringify(await applyPatchPlan(plan,args[1],!args.includes('--apply')),null,2));}if(command==='rebuild-apk'&&args[0])return console.log(JSON.stringify(await rebuildAndroid(args[0],args[1]||'rebuild-output'),null,2));if(command==='verify-apk'&&args[0])return console.log(JSON.stringify(await signAndVerifyAndroid({apk:args[0],workspace:value('--out')||'verified-workspace',keystore:value('--ks'),alias:value('--alias'),storePass:value('--ks-pass'),install:args.includes('--install')}),null,2));if(command==='runtime-android'&&args[0])return console.log(JSON.stringify(await verifyAndroidRuntime(args[0],args[1]||'runtime-output'),null,2));if(command==='recover-mac'&&args[0])return console.log(JSON.stringify(await recoverMac(args[0],args[1]||'recovered-mac'),null,2));if(command==='rebuild-electron'&&args[0])return console.log(JSON.stringify(await rebuildElectron(args[0],args[1]||'electron-build'),null,2));console.error('Commands: recover-apk | index-android | index-manifest | index-dex <dex...> <out> | plan | patch-template | patch | rebuild-apk | verify-apk | runtime-android | recover-mac | rebuild-electron');process.exitCode=2}main().catch(e=>{console.error(e);process.exitCode=1});
